"""baseline schema

Revision ID: baf6279298ce
Revises: 
Create Date: 2026-06-29 22:10:01.943265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baf6279298ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bet_recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('strategy_name', sa.String(length=100), nullable=True),
    sa.Column('matches_json', sa.Text(), nullable=True),
    sa.Column('bet_type', sa.String(length=20), nullable=True),
    sa.Column('total_odds', sa.Float(), nullable=True),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('kelly_fraction', sa.Float(), nullable=True),
    sa.Column('suggested_stake', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('is_won', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=2), nullable=False),
    sa.Column('teams_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_cn', sa.String(length=50), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('fifa_code', sa.String(length=3), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('fifa_ranking', sa.Integer(), nullable=True),
    sa.Column('elo_rating', sa.Float(), nullable=True),
    sa.Column('elo_rating_initial', sa.Float(), nullable=True),
    sa.Column('is_host', sa.Boolean(), nullable=True),
    sa.Column('host_country', sa.String(length=50), nullable=True),
    sa.Column('confederation', sa.String(length=10), nullable=True),
    sa.Column('flag_url', sa.String(length=200), nullable=True),
    sa.Column('total_market_value', sa.Float(), nullable=True),
    sa.Column('avg_age', sa.Float(), nullable=True),
    sa.Column('squad_size', sa.Integer(), nullable=True),
    sa.Column('injury_impact_score', sa.Float(), nullable=True),
    sa.Column('home_advantage_bonus', sa.Float(), nullable=True),
    sa.Column('recent_form_score', sa.Float(), nullable=True),
    sa.Column('recent_goals_scored', sa.Float(), nullable=True),
    sa.Column('recent_goals_conceded', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fifa_code'),
    sa.UniqueConstraint('name_cn')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fifa_match_id', sa.String(length=20), nullable=True),
    sa.Column('match_date', sa.DateTime(), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=True),
    sa.Column('matchday', sa.Integer(), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('venue', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('stadium', sa.String(length=100), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('weather', sa.String(length=30), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('travel_distance_home', sa.Float(), nullable=True),
    sa.Column('travel_distance_away', sa.Float(), nullable=True),
    sa.Column('referee_name', sa.String(length=100), nullable=True),
    sa.Column('referee_nationality', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_fifa_match_id'), 'matches', ['fifa_match_id'], unique=True)
    op.create_index(op.f('ix_matches_match_date'), 'matches', ['match_date'], unique=False)
    op.create_table('team_squad',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=5), nullable=False),
    sa.Column('market_value', sa.Float(), nullable=True),
    sa.Column('is_starter', sa.Boolean(), nullable=True),
    sa.Column('is_injured', sa.Boolean(), nullable=True),
    sa.Column('injury_detail', sa.String(length=200), nullable=True),
    sa.Column('injury_return_date', sa.String(length=20), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.Column('recent_form_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_squad_team_id'), 'team_squad', ['team_id'], unique=False)
    op.create_table('bet_ledger',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=True),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('bet_type', sa.String(length=20), nullable=True),
    sa.Column('selection', sa.String(length=20), nullable=True),
    sa.Column('legs_json', sa.Text(), nullable=True),
    sa.Column('stake', sa.Float(), nullable=True),
    sa.Column('odds', sa.Float(), nullable=True),
    sa.Column('result', sa.String(length=10), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['bet_recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('external_factors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('home_travel_fatigue', sa.Float(), nullable=True),
    sa.Column('away_travel_fatigue', sa.Float(), nullable=True),
    sa.Column('weather_impact_home', sa.Float(), nullable=True),
    sa.Column('weather_impact_away', sa.Float(), nullable=True),
    sa.Column('referee_bias_score', sa.Float(), nullable=True),
    sa.Column('altitude_advantage', sa.Float(), nullable=True),
    sa.Column('home_crowd_support', sa.Float(), nullable=True),
    sa.Column('media_pressure_score', sa.Float(), nullable=True),
    sa.Column('rest_day_advantage', sa.Float(), nullable=True),
    sa.Column('motivation_factor', sa.Float(), nullable=True),
    sa.Column('betting_market_sentiment', sa.Float(), nullable=True),
    sa.Column('manager_change_impact', sa.Float(), nullable=True),
    sa.Column('squad_harmony_score', sa.Float(), nullable=True),
    sa.Column('h2h_advantage', sa.Float(), nullable=True),
    sa.Column('days_since_last_home', sa.Float(), nullable=True),
    sa.Column('days_since_last_away', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_factors_match_id'), 'external_factors', ['match_id'], unique=True)
    op.create_table('match_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('actual_home_score', sa.Integer(), nullable=False),
    sa.Column('actual_away_score', sa.Integer(), nullable=False),
    sa.Column('prediction_accuracy_score', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('odds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('win_odds', sa.Float(), nullable=True),
    sa.Column('draw_odds', sa.Float(), nullable=True),
    sa.Column('lose_odds', sa.Float(), nullable=True),
    sa.Column('handicap', sa.Float(), nullable=True),
    sa.Column('handicap_win', sa.Float(), nullable=True),
    sa.Column('handicap_draw', sa.Float(), nullable=True),
    sa.Column('handicap_lose', sa.Float(), nullable=True),
    sa.Column('over_2_5', sa.Float(), nullable=True),
    sa.Column('under_2_5', sa.Float(), nullable=True),
    sa.Column('goal_0', sa.Float(), nullable=True),
    sa.Column('goal_1', sa.Float(), nullable=True),
    sa.Column('goal_2', sa.Float(), nullable=True),
    sa.Column('goal_3', sa.Float(), nullable=True),
    sa.Column('goal_4', sa.Float(), nullable=True),
    sa.Column('goal_5', sa.Float(), nullable=True),
    sa.Column('goal_6', sa.Float(), nullable=True),
    sa.Column('goal_7plus', sa.Float(), nullable=True),
    sa.Column('score_odds_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odds_match_id'), 'odds', ['match_id'], unique=True)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('prob_home_win', sa.Float(), nullable=True),
    sa.Column('prob_draw', sa.Float(), nullable=True),
    sa.Column('prob_away_win', sa.Float(), nullable=True),
    sa.Column('expected_home_goals', sa.Float(), nullable=True),
    sa.Column('expected_away_goals', sa.Float(), nullable=True),
    sa.Column('score_probs_json', sa.Text(), nullable=True),
    sa.Column('total_goals_probs_json', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('elo_prob_home', sa.Float(), nullable=True),
    sa.Column('elo_prob_draw', sa.Float(), nullable=True),
    sa.Column('elo_prob_away', sa.Float(), nullable=True),
    sa.Column('xgboost_prob_home', sa.Float(), nullable=True),
    sa.Column('xgboost_prob_draw', sa.Float(), nullable=True),
    sa.Column('xgboost_prob_away', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_match_id'), 'predictions', ['match_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictions_match_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_odds_match_id'), table_name='odds')
    op.drop_table('odds')
    op.drop_table('match_results')
    op.drop_index(op.f('ix_external_factors_match_id'), table_name='external_factors')
    op.drop_table('external_factors')
    op.drop_table('bet_ledger')
    op.drop_index(op.f('ix_team_squad_team_id'), table_name='team_squad')
    op.drop_table('team_squad')
    op.drop_index(op.f('ix_matches_match_date'), table_name='matches')
    op.drop_index(op.f('ix_matches_fifa_match_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_table('teams')
    op.drop_table('groups')
    op.drop_table('bet_recommendations')
    # ### end Alembic commands ###
